#!/usr/bin/env python3
"""Generate runtime tables from hash-pinned original / CPython 3.12.8 codecs.
Never modifies the original oracle. --check compares bytes without writing.
"""
import argparse, hashlib, json, platform, sys, unicodedata
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'design'))
from reference_oracle import load_reference, SHA256

def compact(x): return json.dumps(x, ensure_ascii=False, separators=(',', ':'))
def digest(b): return hashlib.sha256(b).hexdigest()
def generate():
    if platform.python_version() != '3.12.8': raise RuntimeError('CPython 3.12.8 required')
    m = load_reference()
    values = [m.jis0213_to_unicode(p,r,c) for p in (1,2) for r in range(1,95) for c in range(1,95)]
    assert values == json.loads((ROOT/'design/fixtures/jis-oracle.json').read_text())['values']
    products = {}
    header = '// Generated by scripts/generate_data.py; CPython 3.12.8. See notices/ and data-provenance.json.\n'
    products['src/data/jisPython312.generated.ts'] = header + 'export const JIS: readonly (string | null)[] = Object.freeze(' + compact(values) + ');\n'
    audit = {}
    for codec, name in [('cp932','cp932'),('shift_jis','shiftJis')]:
        single = []
        for a in range(256):
            try: v = bytes([a]).decode(codec)
            except UnicodeDecodeError: v = None
            single.append(v)
        pairs = {}
        exhaustive = []
        for a in range(256):
            for b in range(256):
                try: v = bytes([a,b]).decode(codec)
                except UnicodeDecodeError: v = None
                exhaustive.append(v)
                if single[a] is None and v is not None: pairs[str(a*256+b)] = v
        products[f'src/encoding/{name}.generated.ts'] = header + f'export const single: readonly (string | null)[] = Object.freeze({compact(single)});\nexport const pairs: Readonly<Record<number, string>> = Object.freeze({compact(pairs)});\n'
        # Independent exhaustive decoded result stream for the test, not the sparse runtime format.
        products[f'tests/fixtures/{codec}-exhaustive.json'] = compact({'single':single,'pairs':exhaustive})+'\n'
        audit[codec] = {'singleCases':256,'pairCases':65536,'singleMapped':sum(x is not None for x in single),'pairMapped':sum(x is not None for x in exhaustive)}
    nd = {str(n):unicodedata.decimal(chr(n)) for n in range(0x110000) if unicodedata.category(chr(n))=='Nd'}
    products['src/data/pythonUnicode.generated.ts'] = header + 'export const decimalValues: Readonly<Record<number, number>> = Object.freeze('+compact(nd)+');\n'
    encoded = {p:s.encode('utf-8') for p,s in products.items()}
    provenance = {'generator':'scripts/generate_data.py','generatorSha256':digest(Path(__file__).read_bytes()),'python':platform.python_version(),'unicode':unicodedata.unidata_version,'sourceSha256':SHA256,'jis':{'entries':len(values),'mapped':sum(v is not None for v in values),'null':values.count(None),'multiCodepoint':sum(v is not None and len(v)>1 for v in values),'compactSha256':digest(compact(values).encode())},'encoding':audit,'files':{p:{'sha256':digest(b),'bytes':len(b)} for p,b in encoded.items()},'licenses':['notices/CPython-LICENSE.txt','notices/Unicode-MAPPINGS.txt','notices/JIS-X0213.txt']}
    encoded['data-provenance.json'] = (json.dumps(provenance,ensure_ascii=False,indent=2)+'\n').encode()
    return encoded
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name, payload in generate().items():
        path=ROOT/name
        if args.check:
            if not path.exists() or path.read_bytes()!=payload: raise RuntimeError('Generated data differs: '+name)
        else: path.parent.mkdir(parents=True,exist_ok=True);path.write_bytes(payload)
    print('PASS: JIS 17,672; CP932 and Shift_JIS each 256 + 65,536; pinned Unicode Nd; '+('byte reproducibility' if args.check else 'generated'))
